spring:
  jackson:
    time-zone: Asia/Ho_Chi_Minh
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 50
          batch_versioned_data: true
        order_updates: true
        order_inserts: true
        generate_statistics: false
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:db_anrealshop_test}?prepareThreshold=0
    username: ${DB_USERNAME:haiemdavang}
    password: ${DB_PASSWORD:haiemdavang}
    driver-class-name: org.postgresql.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true
    properties.mail.debug: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: product-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      auto-offset-reset: earliest
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: true
  elasticsearch:
    username: ${ES_USERNAME:}
    password: ${ES_PASSWORD:}
    uris: http://${ES_HOST:localhost}:${ES_PORT:9200}

  messages:
    basename: errorMessage/MessageString
    encoding: UTF-8

  cloud.gcp:
    project-id: ${GOOGLE_CLOUD_PROJECT_ID}
    credentials:
      location: ${GOOGLE_APPLICATION_CREDENTIALS:}
    location: us-central1


server:
  port: 4141
jwt:
  token:
    expiration: 86400000
    expiration_refresh: 172800000
    cookie_access_name: "ACCESS_TOKEN"
    cookie_refresh_name: "REFRESH_TOKEN"

n8n:
  webhook:
    base-url: ${N8N_BASE_URL:http://localhost:5678}
    chatbot-path: /webhook/chat-box
    timeout: 30

tryonhd.url: ${TRY_ON_HD_URL:http://localhost:8080}

chat:
  encryption:
    key: ${CHAT_ENCRYPTION_KEY:your_chat_encryption_key}

ghn:
  token: ${GHN_TOKEN:your_ghn_token}
  shop_id: ${GHN_SHOPID:your_ghn_shop_id}

sentry:
  dsn: https://ed6f24a0fea1f08db25510b8a3a0cecb@o4511504639131648.ingest.de.sentry.io/4511504679632976
  send-default-pii: true

cloudinary:
  cloud-name: ${CLOUDINARY_NAME:ko_co_dau}
  api-key: ${CLOUDINARY_KEY:ko_co_dau}
  api-secret: ${CLOUDINARY_SECRET:ko_co_dau}
