package com.haiemdavang.AnrealShop.tech.kafka.dto;

public enum ProductSyncActionType {
    CREATE, UPDATE, DELETE, MULTI_DELETE, PRODUCT_UPDATED_VISIBILITY, PRODUCT_UPDATE_MULTI_VISIBILITY,
    PRODUCT_UPDATED_STATUS,

    UPDATE_PRODUCT_EMBEDING
}
