package com.haiemdavang.AnrealShop.utils;

import com.haiemdavang.AnrealShop.exception.AnrealShopException;
import com.haiemdavang.AnrealShop.tech.mail.MailType;

public class MailTemplate {

    public static String getOtpVerificationEmailHTMLVietnamese(String code, String userName) {
        return "<!DOCTYPE html>\r\n"
                + "<html>\r\n"
                + "<head>\r\n"
                + "    <meta charset=\"UTF-8\">\r\n"
                + "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
                + "    <title>Xác Minh OTP - AnrealShop</title>\r\n"
                + "    <style>\r\n"
                + "        * { margin: 0; padding: 0; box-sizing: border-box; }\r\n"
                + "        body {\r\n"
                + "            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Helvetica Neue', Arial, sans-serif;\r\n"
                + "            background-color: #f1f5f9;\r\n"
                + "            padding: 20px;\r\n"
                + "            line-height: 1.6;\r\n"
                + "        }\r\n"
                + "        .container {\r\n"
                + "            max-width: 600px;\r\n"
                + "            margin: 0 auto;\r\n"
                + "            background: #ffffff;\r\n"
                + "            border-radius: 12px;\r\n"
                + "            box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06);\r\n"
                + "            overflow: hidden;\r\n"
                + "        }\r\n"
                + "        .header {\r\n"
                + "            background: linear-gradient(135deg, #0ea5e9, #0284c7);\r\n"
                + "            padding: 32px 24px;\r\n"
                + "            text-align: center;\r\n"
                + "        }\r\n"
                + "        .header-title {\r\n"
                + "            font-size: 24px;\r\n"
                + "            font-weight: 700;\r\n"
                + "            color: #ffffff;\r\n"
                + "            margin-bottom: 8px;\r\n"
                + "        }\r\n"
                + "        .header-icon {\r\n"
                + "            font-size: 48px;\r\n"
                + "            margin-bottom: 12px;\r\n"
                + "        }\r\n"
                + "        .content {\r\n"
                + "            padding: 32px 24px;\r\n"
                + "        }\r\n"
                + "        .greeting {\r\n"
                + "            font-size: 16px;\r\n"
                + "            color: #1e293b;\r\n"
                + "            margin-bottom: 16px;\r\n"
                + "        }\r\n"
                + "        .username {\r\n"
                + "            font-weight: 600;\r\n"
                + "            color: #0ea5e9;\r\n"
                + "        }\r\n"
                + "        .message {\r\n"
                + "            font-size: 14px;\r\n"
                + "            color: #475569;\r\n"
                + "            margin-bottom: 24px;\r\n"
                + "        }\r\n"
                + "        .otp-container {\r\n"
                + "            background: linear-gradient(135deg, #eff6ff, #dbeafe);\r\n"
                + "            border: 2px solid #0ea5e9;\r\n"
                + "            border-radius: 8px;\r\n"
                + "            padding: 24px;\r\n"
                + "            text-align: center;\r\n"
                + "            margin: 24px 0;\r\n"
                + "        }\r\n"
                + "        .otp-label {\r\n"
                + "            font-size: 12px;\r\n"
                + "            color: #64748b;\r\n"
                + "            text-transform: uppercase;\r\n"
                + "            letter-spacing: 0.5px;\r\n"
                + "            margin-bottom: 8px;\r\n"
                + "        }\r\n"
                + "        .otp-code {\r\n"
                + "            font-size: 32px;\r\n"
                + "            font-weight: 700;\r\n"
                + "            color: #0ea5e9;\r\n"
                + "            letter-spacing: 8px;\r\n"
                + "            font-family: 'Courier New', monospace;\r\n"
                + "        }\r\n"
                + "        .warning {\r\n"
                + "            background: #fef3c7;\r\n"
                + "            border-left: 4px solid #f59e0b;\r\n"
                + "            padding: 12px 16px;\r\n"
                + "            border-radius: 4px;\r\n"
                + "            margin: 24px 0;\r\n"
                + "        }\r\n"
                + "        .warning-text {\r\n"
                + "            font-size: 13px;\r\n"
                + "            color: #92400e;\r\n"
                + "        }\r\n"
                + "        .footer {\r\n"
                + "            background: #f8fafc;\r\n"
                + "            padding: 24px;\r\n"
                + "            text-align: center;\r\n"
                + "            border-top: 1px solid #e2e8f0;\r\n"
                + "        }\r\n"
                + "        .footer-text {\r\n"
                + "            font-size: 12px;\r\n"
                + "            color: #64748b;\r\n"
                + "            line-height: 1.5;\r\n"
                + "        }\r\n"
                + "        .brand {\r\n"
                + "            font-weight: 600;\r\n"
                + "            color: #0ea5e9;\r\n"
                + "        }\r\n"
                + "    </style>\r\n"
                + "</head>\r\n"
                + "<body>\r\n"
                + "    <div class=\"container\">\r\n"
                + "        <div class=\"header\">\r\n"
                + "            <div class=\"header-icon\">🔐</div>\r\n"
                + "            <div class=\"header-title\">Xác Minh OTP</div>\r\n"
                + "        </div>\r\n"
                + "        \r\n"
                + "        <div class=\"content\">\r\n"
                + "            <p class=\"greeting\">Xin chào <span class=\"username\">" + userName + "</span>!</p>\r\n"
                + "            \r\n"
                + "            <p class=\"message\">\r\n"
                + "                Chúng tôi đã nhận được yêu cầu xác minh tài khoản của bạn. \r\n"
                + "                Sử dụng mã OTP dưới đây để hoàn tất quá trình xác minh:\r\n"
                + "            </p>\r\n"
                + "            \r\n"
                + "            <div class=\"otp-container\">\r\n"
                + "                <div class=\"otp-label\">Mã xác thực của bạn</div>\r\n"
                + "                <div class=\"otp-code\">" + code + "</div>\r\n"
                + "            </div>\r\n"
                + "            \r\n"
                + "            <div class=\"warning\">\r\n"
                + "                <p class=\"warning-text\">\r\n"
                + "                    ⚠️ <strong>Lưu ý quan trọng:</strong><br>\r\n"
                + "                    • Mã OTP này chỉ có hiệu lực trong <strong>10 phút</strong><br>\r\n"
                + "                    • Vui lòng không chia sẻ mã này với bất kỳ ai<br>\r\n"
                + "                    • Nếu bạn không thực hiện yêu cầu này, hãy bỏ qua email\r\n"
                + "                </p>\r\n"
                + "            </div>\r\n"
                + "        </div>\r\n"
                + "        \r\n"
                + "        <div class=\"footer\">\r\n"
                + "            <p class=\"footer-text\">\r\n"
                + "                Email này được gửi tự động từ hệ thống <span class=\"brand\">AnrealShop</span>.<br>\r\n"
                + "                Vui lòng không trả lời email này.\r\n"
                + "            </p>\r\n"
                + "            <p class=\"footer-text\" style=\"margin-top: 8px;\">\r\n"
                + "                © 2025 AnrealShop. All rights reserved.\r\n"
                + "            </p>\r\n"
                + "        </div>\r\n"
                + "    </div>\r\n"
                + "</body>\r\n"
                + "</html>";
    }

    public static String getEmailVerificationHTMLVietnamese(String code, String userName) {
        return "<!DOCTYPE html>\r\n"
                + "<html>\r\n"
                + "<head>\r\n"
                + "    <meta charset=\"UTF-8\">\r\n"
                + "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
                + "    <title>Xác Minh Email - AnrealShop</title>\r\n"
                + "    <style>\r\n"
                + "        * { margin: 0; padding: 0; box-sizing: border-box; }\r\n"
                + "        body {\r\n"
                + "            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Helvetica Neue', Arial, sans-serif;\r\n"
                + "            background-color: #f1f5f9;\r\n"
                + "            padding: 20px;\r\n"
                + "            line-height: 1.6;\r\n"
                + "        }\r\n"
                + "        .container {\r\n"
                + "            max-width: 600px;\r\n"
                + "            margin: 0 auto;\r\n"
                + "            background: #ffffff;\r\n"
                + "            border-radius: 12px;\r\n"
                + "            box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06);\r\n"
                + "            overflow: hidden;\r\n"
                + "        }\r\n"
                + "        .header {\r\n"
                + "            background: linear-gradient(135deg, #0ea5e9, #0284c7);\r\n"
                + "            padding: 32px 24px;\r\n"
                + "            text-align: center;\r\n"
                + "        }\r\n"
                + "        .header-title {\r\n"
                + "            font-size: 24px;\r\n"
                + "            font-weight: 700;\r\n"
                + "            color: #ffffff;\r\n"
                + "            margin-bottom: 8px;\r\n"
                + "        }\r\n"
                + "        .header-icon {\r\n"
                + "            font-size: 48px;\r\n"
                + "            margin-bottom: 12px;\r\n"
                + "        }\r\n"
                + "        .content {\r\n"
                + "            padding: 32px 24px;\r\n"
                + "        }\r\n"
                + "        .greeting {\r\n"
                + "            font-size: 16px;\r\n"
                + "            color: #1e293b;\r\n"
                + "            margin-bottom: 16px;\r\n"
                + "        }\r\n"
                + "        .username {\r\n"
                + "            font-weight: 600;\r\n"
                + "            color: #0ea5e9;\r\n"
                + "        }\r\n"
                + "        .message {\r\n"
                + "            font-size: 14px;\r\n"
                + "            color: #475569;\r\n"
                + "            margin-bottom: 24px;\r\n"
                + "        }\r\n"
                + "        .otp-container {\r\n"
                + "            background: linear-gradient(135deg, #eff6ff, #dbeafe);\r\n"
                + "            border: 2px solid #0ea5e9;\r\n"
                + "            border-radius: 8px;\r\n"
                + "            padding: 24px;\r\n"
                + "            text-align: center;\r\n"
                + "            margin: 24px 0;\r\n"
                + "        }\r\n"
                + "        .otp-label {\r\n"
                + "            font-size: 12px;\r\n"
                + "            color: #64748b;\r\n"
                + "            text-transform: uppercase;\r\n"
                + "            letter-spacing: 0.5px;\r\n"
                + "            margin-bottom: 8px;\r\n"
                + "        }\r\n"
                + "        .otp-code {\r\n"
                + "            font-size: 32px;\r\n"
                + "            font-weight: 700;\r\n"
                + "            color: #0ea5e9;\r\n"
                + "            letter-spacing: 8px;\r\n"
                + "            font-family: 'Courier New', monospace;\r\n"
                + "        }\r\n"
                + "        .info-box {\r\n"
                + "            background: #f0f9ff;\r\n"
                + "            border-left: 4px solid #0ea5e9;\r\n"
                + "            padding: 16px;\r\n"
                + "            border-radius: 4px;\r\n"
                + "            margin: 24px 0;\r\n"
                + "        }\r\n"
                + "        .info-text {\r\n"
                + "            font-size: 13px;\r\n"
                + "            color: #075985;\r\n"
                + "            line-height: 1.6;\r\n"
                + "        }\r\n"
                + "        .warning {\r\n"
                + "            background: #fef3c7;\r\n"
                + "            border-left: 4px solid #f59e0b;\r\n"
                + "            padding: 12px 16px;\r\n"
                + "            border-radius: 4px;\r\n"
                + "            margin: 24px 0;\r\n"
                + "        }\r\n"
                + "        .warning-text {\r\n"
                + "            font-size: 13px;\r\n"
                + "            color: #92400e;\r\n"
                + "        }\r\n"
                + "        .footer {\r\n"
                + "            background: #f8fafc;\r\n"
                + "            padding: 24px;\r\n"
                + "            text-align: center;\r\n"
                + "            border-top: 1px solid #e2e8f0;\r\n"
                + "        }\r\n"
                + "        .footer-text {\r\n"
                + "            font-size: 12px;\r\n"
                + "            color: #64748b;\r\n"
                + "            line-height: 1.5;\r\n"
                + "        }\r\n"
                + "        .brand {\r\n"
                + "            font-weight: 600;\r\n"
                + "            color: #0ea5e9;\r\n"
                + "        }\r\n"
                + "    </style>\r\n"
                + "</head>\r\n"
                + "<body>\r\n"
                + "    <div class=\"container\">\r\n"
                + "        <div class=\"header\">\r\n"
                + "            <div class=\"header-icon\">📧</div>\r\n"
                + "            <div class=\"header-title\">Xác Minh Email</div>\r\n"
                + "        </div>\r\n"
                + "        \r\n"
                + "        <div class=\"content\">\r\n"
                + "            <p class=\"greeting\">Xin chào <span class=\"username\">" + userName + "</span>!</p>\r\n"
                + "            \r\n"
                + "            <p class=\"message\">\r\n"
                + "                Cảm ơn bạn đã đăng ký tài khoản tại <span class=\"brand\">AnrealShop</span>. \r\n"
                + "                Để hoàn tất quá trình đăng ký và kích hoạt tài khoản, vui lòng sử dụng mã xác thực dưới đây:\r\n"
                + "            </p>\r\n"
                + "            \r\n"
                + "            <div class=\"otp-container\">\r\n"
                + "                <div class=\"otp-label\">Mã xác thực email</div>\r\n"
                + "                <div class=\"otp-code\">" + code + "</div>\r\n"
                + "            </div>\r\n"
                + "            \r\n"
                + "            <div class=\"info-box\">\r\n"
                + "                <p class=\"info-text\">\r\n"
                + "                    ℹ️ <strong>Hướng dẫn:</strong><br>\r\n"
                + "                    1. Nhập mã xác thực vào trang đăng ký<br>\r\n"
                + "                    2. Nhấn nút \"Xác nhận\" để hoàn tất<br>\r\n"
                + "                    3. Sau khi xác minh, bạn có thể đăng nhập và bắt đầu mua sắm\r\n"
                + "                </p>\r\n"
                + "            </div>\r\n"
                + "            \r\n"
                + "            <div class=\"warning\">\r\n"
                + "                <p class=\"warning-text\">\r\n"
                + "                    ⚠️ <strong>Lưu ý quan trọng:</strong><br>\r\n"
                + "                    • Mã xác thực này chỉ có hiệu lực trong <strong>10 phút</strong><br>\r\n"
                + "                    • Vui lòng không chia sẻ mã này với bất kỳ ai<br>\r\n"
                + "                    • Nếu bạn không thực hiện yêu cầu này, hãy bỏ qua email\r\n"
                + "                </p>\r\n"
                + "            </div>\r\n"
                + "        </div>\r\n"
                + "        \r\n"
                + "        <div class=\"footer\">\r\n"
                + "            <p class=\"footer-text\">\r\n"
                + "                Email này được gửi tự động từ hệ thống <span class=\"brand\">AnrealShop</span>.<br>\r\n"
                + "                Vui lòng không trả lời email này.\r\n"
                + "            </p>\r\n"
                + "            <p class=\"footer-text\" style=\"margin-top: 8px;\">\r\n"
                + "                © 2025 AnrealShop. All rights reserved.\r\n"
                + "            </p>\r\n"
                + "        </div>\r\n"
                + "    </div>\r\n"
                + "</body>\r\n"
                + "</html>";
    }

    public static String getEmailHTML(String code, String email, MailType mailType) {
        switch (mailType){
            case VERIFY_EMAIL -> {
                return getEmailVerificationHTMLVietnamese(code, email);
            }
            case RESET_PASSWORD -> {
                return getOtpVerificationEmailHTMLVietnamese(code, email);
            }
            default -> throw new AnrealShopException("Unsupported mail type: " + mailType);
        }
    }
}